### ISSUE TITLE
Project 3C Todo

### ISSUE THREAD

**Issue by Jon204D** [grammerjam/tk-main#10]
- [x] Fix Exp Date on card view
- [x] Space out card numbers by every four digits
- [x] Work on Mobile View
- [x] Pass card details from card info to payment confirmation page
- [x] Work on date validation for card exp
- [x] Redirect to the confirmation page if validation is approved

**Comment by Jon204D** [comment]
Completing tasks on [https://github.com/grammerjam/tk-main/issues/11](https://github.com/grammerjam/tk-main/issues/11).
