### ISSUE TITLE
Thursday ToDo

### ISSUE THREAD

**Issue by jayembailey** [grammerjam/tk-main#11]
- [x] make cards move with page resizing
- [x] consolidate css
- [x] format for mobile
- [x] Fix page container height issue for Desktop & Mobile
